TEIC/Stylesheets

common/functions.xsl

I encountered a problem with tei:pb when transforming to XML-FO. When tei:pb is direct child of tei:front, tei:body, or tei:back it was outputted as fo:inline. This rendered the XML-FO invalid, as fo:inline may not be direct child of fo:flow.
The function tei:isInline() is called with the parent node of tei:pb as parameter (tei:front | tei:body | tei:back in the described cases). Adding xsl:when for self::(tei:front | tei:body | tei:back) fixed the issue.
Moreover as tei:pb should be handled equally in tei:front, tei:body, tei:back xsl:when statements were added for parent::(tei:front | tei:back).

Fix tei:isInline() return 'false' on (parent:: | self::)(tei:front | tei:body | tei:back)

---

fo/fo_param.xsl

$footNoteSize and $footNoteNumSize were being calculated without
appending dimension. Added 'pt' after value.

add 'pt' to footNoteSize and footNoteNumSize

---

fo/fo_param.xsl

was undone by a previous faulty merge, sorry
I checked the previous merges and realised, that when I had unintentionally merged the initial pull-request to one of my other pull-requests and undone it, it wasn't a reset but a revert, sorry for the confusion...
Merging this will fix it -)

fix FO footnoteSize and footnotenumSize

---

fo/fo_textstructure.xsl

reverse order of processing tei:head and generation of fo:markers in order to conform to xsl-fo 1.1 definition, that markers have to be initial childern.
closes #74

fo:marker position

---

fo/fo_core.xsl
fo/fo_param.xsl

as discussion in #73 tended towards an inclusive rather than an exclusive approach,at the moment, this feature will only be applied to tei:p[not(parent::tei:note)]

add parameters for front, body, back line-height

---

fo/fo_core.xsl
fo/fo_param.xsl
fo/fo_textstructure.xsl

added a parameter that allows different configuration options for line-height application on tei:p, footnotes, and blockquote
closes #82

add paramete for FO lineheight application rules

---

common/teianttasks.xml
odds/odd2odd.xsl

I was having trouble with relative filenames given as @source on `<schemaSpec>` when trying to generate a RelaxNG schema from an ODD. ODD processing failed in odd2odd.xsl with the error 'Source … not readable'. (Absolute paths did work though)
It turned out, the param `currentDir` wasn't set at all so I added it to the ANT macro def. 
I didn't investigate, though, if that fix could apply to other transformations, as well?!

added param for currentDir and added slash as separator

---

docx/from/functions.xsl

So my Word document has this element:
```
<w:r w:rsidR="00E86F6B">
<w:instrText>HYPERLINK \l "_ENREF_18" \o "Temporary, 2003 #8947"</w:instrText>
</w:r>
```
Which means that the current method of checking only for " HYPERLINK" fails, and produces several hyperlinks in the end, as each space separated entry gets converted into a separate link. The example above will result in something like (after Docx to TEI to XHTML):
```
[<a class="link_ref" href="HYPERLINK">18</a>, <a class="link_ref" href="\l">18</a>, <a class="link_ref" href="&#34;_ENREF_18&#34;">18</a>, <a class="link_ref" href="\o">18</a>, <a class="link_ref" href="&#34;Temporary,">18</a>, <a class="link_ref" href="2003">18</a>, and 18]
```
I've tried to find a reference in the standard that a leading space in `instrText` is …

Trim leading whitespace in instrText, which may or may not be present.

---

docx/from/pass2.xsl

I have a Docx document like this:
```
<w:r w:rsidR="00A134F5">
<w:rPr>
<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:cs="Times New Roman"/>
</w:rPr>
<w:fldChar w:fldCharType="begin"/>
</w:r>
<w:r w:rsidR="0003278C">
<w:rPr>
<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:cs="Times New Roman"/>
</w:rPr>
<w:instrText xml:space="preserve"> ADDIN EN.CITE &lt;EndNote&gt;&lt;Cite&gt;&lt;Author&gt;Heisman&lt;/Author&gt;&lt;Year&gt;2011&lt;/Year&gt;&lt;RecNum&gt;8054&lt;/RecNum&gt;&lt;DisplayText&gt;[1]&lt;/DisplayText&gt;&lt;record&gt;&lt;rec-number&gt;8054&lt;/rec-number&gt;&lt;foreign-keys&gt;&lt;key app="EN" db-id="f5zt9sprdvpxwpezx21xf0zzevfetw0weprs"&gt;8054&lt;/key&gt;&lt;/foreign-keys&gt;&lt;ref-type …
```

Add text from the node, in addition to the processed bibliography instruction.

---

latex/latex_core.xsl

obviously the command subsunsection doesn’t exist in LaTeX
best regards, and thanks a lot for the good work

correct a typo in a LaTeX command

---

odds/guidelines.xsl

from section „Works Cited in Examples in these Guidelines“.
This fix addresses the current Jenkins failures by removing dead links from the bibliography. This just occurred in the English version but has been around in other Guideline languages longer, see e.g. entry 17 at http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/BIB.html. Those backlinks (e.g. http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-div5.html#index-egXML-d51e50602) point at examples that are not present in the French language version.
NB: My fix only removes those links but keeps the entry in the bibliography.

removes dead backlinks from bibliography

---

css/tei.css
html/html_core.xsl

According to the decision of the Stylesheet co-op group, the output from `<address>` is changed to `<span class="address">` and the CSS selector span.address is added, see the discussion on: https://github.com/TEIC/Stylesheets/issues/261

TEI address element is wrongly converted to HTML address element (#261)

---

profiles/jtei/jtei.common.xsl
profiles/jtei/openedition/to.xsl
profiles/jtei/pdf/to.xsl

-fixes to OpenEdition rendition of lists (after OpenEdition fix of  https://github.com/OpenEdition/tei.openedition/issues/4)
-don't label list headings

-updated to OpenEdition-1.5.2

---

html/html_core.xsl

In the digital edition http://nl.ijs.si/e-zrc/kapelski/index-en.html we now make reference (via ref/@target) to ab/@xml:id, which didn't work in HTML because tei:ab/@xml:id didn't get mapped to html:div/@id. And this is now fixed.
Btw., this is my first pull request, so I hope it is kosher!

Add makeAnchor to tei:ab where it generates html:div

---

README.md
tools/oddbyexample.xsl

cleaned up readme
made minor changes to L424 and L417 in 'oddbyexample' to facilitate it's use in tei-publisher (PR pending there)
You can keep this open until the tei-publisher changes are live, or since there are no functional changes feel free to merge.

Minor changes for easier use with tei-publisher

---

Test/Makefile

Recent version of debian-based OSes have software changes which result in the sequence of items in a zip file listing being in a different order from those in older versions. When we do diffs of file listings against expected-results in the Stylesheets Tests, those tests fail because the expected-results are in a different order. The sequence of items is insignificant, so sorting both the test file and the expected-results file before diffing results in an equally rigorous test but makes it more robust against software changes, allowing the tests to succeed on (for example) Ubuntu 18.04, the current LTS.

Implementation of sorted diffing to make Test more robust against software version changes.

---

Makefile
Test/Makefile
Test/expected-results/test.rng
Test/expected-results/test15.odd.html
Test/expected-results/test15.odd.rnc
Test/expected-results/test21.odd.rnc
Test/expected-results/test30.rnc
Test/expected-results/test33.json
Test/expected-results/test33.rnc
Test/expected-results/test34.combined.json
Test/expected-results/test34.json
Test/expected-results/test34.rnc
Test/expected-results/test35.rnc
Test/expected-results/testdrama.compiled.xml
bin/transformtei
common/functions.xsl
odds/odd2odd.xsl
tools/getnames.xsl
tools/oddbyexample.xsl

This PR fixes the current build process issue due to http->http redirects for http://www.tei-c.org/Vault/P5/current/xml/tei/odd/p5subset.xml. 
Rather than changing all calls in the respective stylesheets I tried to improve the build process by adding and propagating a `DEFAULTSOURCE` parameter, so finally it's possible to run the tests against a local source of your choice! 
There were several changes needed:
* `tools/getnames.xsl`: replace hard coded value with a parameter that can be overwritten from outside
* `bin/transformtei`: support remote resource for `--localsource` parameter
* `Makefile` and `Test/Makefile`: add defaultSource parameter per default to every call to saxon, and add the `--localsource` parameter per default to every call to `/$(BINDIR)/teitoXXX` 
* some updates to …

set localsource parameter once for build process 

---

Test/expected-results/test7.xml
odt/odttotei.xsl

This PR addresses #358 and adds `<tei:pb>` (when indicated by odt styles) for
* paragraphs `<text:p>`
* tables `<table:table>`
* lists; admittedly not very elegant, because the page break is actually inserted via the `<text:p>` of the first list item. Thus, the `<tei:pb>` ends up _within_ the `<tei:list>`

add support for hard page breaks in odttotei

---

common/functions.xsl
odds/extract-sch.xsl
odds/odd2odd.xsl

that originated from https://github.com/TEIC/Roma/issues/26
While it looks like a simple fix, I'm not 150% sure about the implications, so feedback from @sydb who's done more work on Schematron is highly appreciated.
Also, @cmsmcq has a local fix for the issue at hand. Maybe he can add to that as well?

make sure to only pass one prefix to `concat()`, fixes 366

---

odds/teiodds.xsl

I wanted the Relax-NG output from my ODD to render ref[@target] as link and gi | att as code, adding the three small templates does it for this purpose and gets visualized in oXygen, but I ignore other possible implications. I have tested modifying my local version of the stylesheets.

adding rendering of ref, gi and att inside desc

---

odds/teiodds.xsl

This PR intends to communicate the cause of failure more clearly in cases where external modules are referenced and the resource is not available/parseable during conversion.
We found this with @textloop when trying to include
```xml
<moduleRef url="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/mathml2-main.rng"/>
```
which is now (after the February incident?) forwarded to https.
**Error message before this change:**
```
System ID: /Volumes/WORKBENCH/gitlab/testing/schema/tei_hal.odd
Scenario: TEI ODD to RELAX NG XML - Copy
Build file: /Applications/oXygen XML/oxygen 21.0/frameworks/tei/xml/tei/stylesheet/relaxng/build-to.xml
Engine name: ANT
Severity: fatal
Description: Transformation failed. /Applications/oXygen XML/oxygen …
```

Improve error handling for faulty moduleRef uri

---

epub3/tei-to-epub3.xsl

This PR fixes the issue #312 with incorrect relative paths to CSSs in the EPub transformation by simply providing full URLs.
Since those files get included via `unparsed-text()` it is not possible to a) use xml catalogs (see https://www.saxonica.com/html/documentation/sourcedocs/xml-catalogs.html) and b) to follow redirects.

change to full URLs for CSS imports
